FROM node:20.15.0-alpine3.20
WORKDIR /usr/src/app

ARG DB_HOST
ARG DB_PASS
ARG DB_NAME
ARG DB_USER
ARG SECRET

ENV DB_HOST=$DB_HOST
ENV DB_PASS=$DB_PASS
ENV DB_NAME=$DB_NAME
ENV DB_USER=$DB_USER
ENV SECRET=$SECRET

COPY package*.json ./
RUN npm install
COPY . .

EXPOSE 4000
CMD [ "node", "index.js"]